v1.4.4

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,14 +4,14 @@ HEADER(){
 printf "\e[96m                                           
  _____ _____ _____ __    _____ _____ __ __ 
 |  _  |  |  |  _  |  |  |  _  |   | |  |  |
-|   __|     |     |  |__|     | | | |-   -|v1.2
+|   __|     |     |  |__|     | | | |-   -|v1.3
 |__|  |__|__|__|__|_____|__|__|_|___|__|__|installation!\e[0m\n\n"
 }
 
 HEADER
 
 USAGE(){
-printf "Usage: $(basename $0) [OPTION]\n\nOptions:\n\n	-0 [token]	Slack Configuration\n	-1		Tools Installation\n 	-2		PHALANX Installation\n\n"
+printf "Usage: $(basename $0) [OPTION]\n\nOptions:\n\n	-0 [token]	Slack Configuration\n	-1 [token]	PHALANX-API Configuration\n	-2		Tools Installation\n 	-3		PHALANX Installation\n\n"
 }
 
 PATHTOSCRIPTS="$PWD/cmd"
@@ -31,6 +31,16 @@ then
 	fi
 elif [[ "${1}" = "-1" ]]
 then
+	if [[ -z "${2}" ]]
+	then
+		printf "\e[31m$(basename $0): error: please provide phalanx token\e[0m\n" >&2
+		exit 1
+	else
+		echo "${2}" 1> $PATHTOSCRIPTS/phalanx.token
+		printf "\e[32m[*] Phalanx has been configured\e[0m\n"
+	fi
+elif [[ "${1}" = "-2" ]]
+then
 	printf "\e[93m[-] Dependencies Installation Start\e[0m\n"
 	sudo apt-get install -y snapd
 	echo -ne '\e[92m########                   (33%)\e[0m\r'
@@ -42,8 +52,18 @@ then
 	echo -ne '\e[92m########################## (100%)\e[0m\r'
 	echo -ne '\n'
 	printf "\e[32m[+] Dependencies Installation End\e[0m\n"
-elif [[ "${1}" = "-2" ]]
+elif [[ "${1}" = "-3" ]]
 then
+	if [[ ! -f "$PATHTOSCRIPTS/slack.token" ]]
+	then
+		printf "\e[31m$(basename $0): error: slack token is required\e[0m\n" >&2
+		exit 1
+	fi
+	if [[ ! -f "$PATHTOSCRIPTS/phalanx.token" ]]
+	then
+		printf "\e[31m$(basename $0): error: phalanx token is required\e[0m\n" >&2
+		exit 1
+	fi
 	printf "\e[93m[-] PHALANX Installation Start\e[0m\n"
 	chmod 777 cmd
 	echo -ne '\e[92m########                   (33%)\e[0m\r'
diff --git a/phalanx b/phalanx
--- a/phalanx
+++ b/phalanx
@@ -6,7 +6,7 @@ HEADER(){
 	   / __ \/ / / /   |  / /   /   |  / | / / |/ /
 	  / /_/ / /_/ / /| | / /   / /| | /  |/ /|   / 
 	 / ____/ __  / ___ |/ /___/ ___ |/ /|  //   |  
-	/_/   /_/ /_/_/  |_/_____/_/  |_/_/ |_//_/|_|v1.4\e[0m\n\n"
+	/_/   /_/ /_/_/  |_/_____/_/  |_/_/ |_//_/|_|v1.5.2\e[0m\n\n"
 }
 
 USAGE(){
@@ -16,7 +16,7 @@ printf "Usage: $(basename $0) DOMAIN [OPTION]\n\nOptions:\n\n	-1	STAGE-1 Extract
 HEADER
 
 #SCRIPTPATH
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 
 #PATH
 MAINPATH="$HOME/${1}"
@@ -30,8 +30,9 @@ PATHGITHOUND="${MAINPATH}/git-hound"
 #FILEPATH
 FULLFILEOUT="${MAINPATH}/${1}"
 
-#SCRIPTPATH
+#TOKENPATH
 PATHTOSLACKTOKEN="${PATHTOSCRIPTS}/slack.token"
+PATHTOPHALANXTOKEN="${PATHTOSCRIPTS}/phalanx.token"
 
 #BAKPATH
 BAKMAINPATH="${MAINPATH}/${1}.bak"
@@ -75,7 +76,7 @@ printf "\e[33m[*] Sublist3r process end\e[0m\n"
 #Subscraper
 $PATHTOSCRIPTS/SUBSENUM/subscraper/subscraper.py $1 1> $SUBCRAPERBAK
 printf "\e[33m[*] Subscraper process end\e[0m\n"
-rm $HOME/subscraper_report.txt
+rm "$HOME/subscraper_report.txt"
 #OUTPUT Process Start
 #OUTPUT Formation
 SUBCRAPERCAT=$(echo $SUBCRAPERBAK | awk '{print $2}' | head -n -4 | tail -n +10)
@@ -91,7 +92,6 @@ do
 		echo $L 1>> $FULLFILEOUTBAK
 	fi
 done
-sleep 5
 #OUTPUT Process End
 cat $FULLFILEOUTBAK | $PATHTOSCRIPTS/SUBSENUM/httprobe/main -t 20000 | sed 's#https*://##g'| sort -u 1> $FULLFILEOUT
 if [[ -f "$PATHTOSLACKTOKEN" ]]
@@ -101,7 +101,10 @@ then
 	curl -s -F token=$(cat $PATHTOSLACKTOKEN) -F channel=subdomains -F text="Your ${1} subdomains:${NEWLINE}$(cat $FULLFILEOUT)" https://slack.com/api/chat.postMessage &>/dev/null
 	curl -s -F token=$(cat $PATHTOSLACKTOKEN) -F channel=subdomains -F text="💻⭐💻⭐💻⭐💻⭐💻⭐💻⭐💻⭐" https://slack.com/api/chat.postMessage &>/dev/null
 fi
-python3 $PATHTOSCRIPTS/phalanx-api.py $1 $FULLFILEOUT &>/dev/null
+if [[ -f "$PATHTOPHALANXTOKEN" ]]
+then
+	python3 $PATHTOSCRIPTS/phalanx-api.py $1 $FULLFILEOUT
+fi
 printf "\e[32m[+] Subdomains Enumeration process end\e[0m\n"
 }
 
@@ -119,7 +122,10 @@ do
 		printf "${L} (${CNAME})\n${IP} (${PTR})\n\n" 1>> "${FULLFILEOUT}-CNAME-PTR"
 	fi
 done
-python3 $PATHTOSCRIPTS/dominator.py $FULLFILEOUT
+if [[ -f "$PATHTOSLACKTOKEN" ]]
+then
+	python3 $PATHTOSCRIPTS/dominator.py $FULLFILEOUT
+fi
 printf "\e[32m[+] DNS Enumeration process end\e[0m\n"
 }
 
@@ -132,7 +138,7 @@ $PATHTOSCRIPTS/SCREENSENUM/gowitness/main single --destination $PATHSCREENSHOTS 
 done
 $PATHTOSCRIPTS/SCREENSENUM/gowitness/main report generate -n $FULLFILEOUT &>/dev/null
 printf "\e[32m[+] Screenshots Enumeration process end\e[0m\n"
-rm $HOME/gowitness.db
+rm "$HOME/gowitness.db"
 }
 
 EXTRACTION(){
@@ -187,6 +193,9 @@ PATHCREATOR(){
 if [ ! -d "${MAINPATH}" ]
 then
 	mkdir "${MAINPATH}" && mkdir "${PATHSCREENSHOTS}" && mkdir "${PATHLINKFINDER}" && mkdir "${PATHGITHOUND}" && mkdir "${BAKMAINPATH}" && mkdir "${BAKPATHSUBENUM}" && mkdir "${BAKPATHPARAMSPIDER}"
+else
+	printf "\e[31m$(basename $0): error: this domain path already exists, please provide other domain\e[0m\n" >&2
+	exit 1
 fi
 }
 
@@ -200,11 +209,8 @@ else
 			SECONDS=0
 			PATHCREATOR
 			SUBSENUM $1
-			sleep 1
 			DNSENUM
-			sleep 1
 			SCREENSENUM $1
-			sleep 1
 			EXTRACTION $1
 			ENDTIME=$[$SECONDS/60]
 			printf "\e[93m$(basename $0): Your process time is ${ENDTIME} m\e[0m\n"
